{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "badtakestream.serviceAccountName" . }}
  labels:
{{ include "badtakestream.labels" . | indent 4 }}
{{- end -}}
