apiVersion: v1
kind: Service
metadata:
  name: {{ include "badtakestream.fullname" . }}-web
  labels:
{{ include "badtakestream.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "badtakestream.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: web